language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
script:
  - py.test --tb=native seep
  - python -m doctest README.rst
